export const cartList = [
  {
    id: 1,
    name: "Diesel Sport",
    photoName: "shoe.jpg",
    color: ["black"],
    price: 1572,
    tax: 25,
    amount: 1,
  },
  {
    id: 2,
    name: "Adidas Court platform",
    photoName: "shoe2.jpg",
    color: ["black", "white"],
    price: 800,
    tax: 5,
    amount: 1,
  },
  {
    id: 3,
    name: "Nike Airmax",
    photoName: "shoe3.jpg",
    color: ["black"],
    price: 2100,
    tax: 50,
    amount: 1,
  },
  {
    id: 4,
    name: "Solomon SM",
    photoName: "shoe4.jpg",
    color: ["black"],
    price: 3400,
    tax: 100,
    amount: 1,
  },
];
